import {initFirebase,getUid,getDb} from "./firebase/database.js";import {createRoom,joinRoom,subscribeRoom,startGame,placeBid,resolveAuction,submitTeam} from "./firebase/rooms.js";import {PLAYERS} from "./data/players.js";import {scoreTeam} from "./game/scoring.js";import {lobbyView} from "./ui/lobby.js";import {auctionView} from "./ui/auction-ui.js";import {teamView} from "./ui/team-ui.js";import {resultsView} from "./ui/results-ui.js";import {ref,runTransaction} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
const $=s=>document.querySelector(s),screen=$("#screen"),toast=$("#toast"),playersById=Object.fromEntries(PLAYERS.map(p=>[p.id,p]));let room=null,unsub=null,code=sessionStorage.getItem("caa_room")||"",teamSize=5;window.__roomCode=code;
const msg=m=>{toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)};const status=(s,g=false)=>{$("#connectionStatus").textContent=s;$ ("#connectionStatus").style.color=g?"#46e36d":""};
function home(){screen.innerHTML=`<div class="center"><section class="hero"><div class="logo-mark">🏏</div><div class="eyebrow">PRIVATE MULTIPLAYER · 3–5 FRIENDS</div><h1>Cricket<br><span class="accent">Auction Arena</span></h1><p>Build your squad, outbid your friends and submit your best Playing 5 or Playing 11. Every player starts with ₹500 virtual budget.</p><div class="actions"><button id="createHome" class="btn primary">CREATE ROOM</button><button id="joinHome" class="btn ghost">JOIN ROOM</button></div></section></div>`;$("#createHome").onclick=create;$("#joinHome").onclick=join}
function create(){screen.innerHTML=`<section class="card"><div class="eyebrow">NEW GAME</div><h1>Create Room</h1><div class="field"><label>Your name</label><input id="name" maxlength="18" placeholder="e.g. Kartik"></div><div class="field"><label>Team size</label><div class="seg"><button data-s="5" class="active">Playing 5</button><button data-s="11">Playing 11</button></div></div><button id="go" class="btn primary">CREATE ROOM</button><button id="back" class="btn ghost">BACK</button></section>`;$("#screen").querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>{teamSize=+b.dataset.s;document.querySelectorAll("[data-s]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("#go").onclick=async()=>{try{const n=$("#name").value.trim();if(!n)throw Error("Enter your name.");code=await createRoom(n,teamSize);sessionStorage.setItem("caa_room",code);subscribe()}catch(e){msg(e.message)}};$("#back").onclick=home}
function join(){screen.innerHTML=`<section class="card"><div class="eyebrow">JOIN GAME</div><h1>Join Room</h1><div class="field"><label>Your name</label><input id="name" maxlength="18" placeholder="e.g. Player 2"></div><div class="field"><label>Room code</label><input id="code" maxlength="5" placeholder="K7P4X"></div><button id="go" class="btn primary">JOIN ROOM</button><button id="back" class="btn ghost">BACK</button></section>`;$("#go").onclick=async()=>{try{const n=$("#name").value.trim(),c=$("#code").value.trim().toUpperCase();if(!n||c.length!==5)throw Error("Enter your name and 5-character room code.");code=await joinRoom(c,n);sessionStorage.setItem("caa_room",code);subscribe()}catch(e){msg(e.message)}};$("#back").onclick=home}
function subscribe(){if(unsub)unsub();window.__roomCode=code;status("Syncing…");unsub=subscribeRoom(code,r=>{room=r;if(!r){sessionStorage.removeItem("caa_room");code="";status("Disconnected");home();return}status("Live",true);if(r.status==="AUCTION"&&getUid()===r.hostId)maybeResolve();if(r.status==="TEAM_REVIEW")maybeResults();render()})}
function render(){if(!room)return home();if(room.status==="LOBBY")return lobby();if(room.status==="AUCTION")return auction();if(room.status==="TEAM_REVIEW")return team();if(room.status==="RESULTS")return results()}
function lobby(){screen.innerHTML=lobbyView({room,isHost:room.hostId===getUid()});$("#startBtn")?.addEventListener("click",async()=>{try{await startGame(code)}catch(e){msg(e.message)}});$("#leaveBtn").onclick=()=>{if(unsub)unsub();sessionStorage.removeItem("caa_room");room=null;code="";home()};$(".copy-btn")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(code);msg("Room code copied")}catch{msg(code)}})}
function auction(){const me=room.players[getUid()],p=playersById[room.auction.currentPlayerId],left=Math.max(0,Math.ceil((+room.auction.deadline-Date.now())/1000));room.__players=playersById;screen.innerHTML=auctionView({room,me,player:p,remaining:left});$("#bidBtn").onclick=async()=>{try{await placeBid(code,+$("#bidInput").value)}catch(e){msg(e.message)}};$("#passBtn").onclick=()=>{};if(left<=0&&getUid()===room.hostId)maybeResolve();else setTimeout(()=>room?.status==="AUCTION"&&render(),500)}
async function maybeResolve(){try{await resolveAuction(code)}catch(e){console.error(e)}}
function team(){const me=room.players[getUid()];screen.innerHTML=teamView({room,me,playersById});$("#submitBtn")?.addEventListener("click",async()=>{try{await submitTeam(code);msg("Team locked") }catch(e){msg(e.message)}})}
async function maybeResults(){const ps=Object.values(room.players||{});if(ps.length>=3&&ps.every(p=>p.submitted)){const scores=Object.fromEntries(ps.map(p=>[p.id,scoreTeam(room.teamSize,p.squad,playersById)]));await runTransaction(ref(getDb(),`rooms/${code}`),r=>{if(!r||r.status!=="TEAM_REVIEW")return;r.status="RESULTS";r.scores=scores;r.lastActivityAt={".sv":"timestamp"};return r})}}
function results(){screen.innerHTML=resultsView({room,scores:room.scores||{}});$("#playAgainBtn").onclick=async()=>{try{const old=code;await import("./firebase/rooms.js").then(m=>m.endRoom(old))}catch(e){console.warn(e)}finally{if(unsub)unsub();sessionStorage.removeItem("caa_room");room=null;code="";home()}}}
(async()=>{try{await initFirebase();status("Ready",true);code?subscribe():home()}catch(e){status("Setup needed");screen.innerHTML=`<div class="center"><section class="card"><div class="eyebrow">FIREBASE SETUP</div><h1>Almost ready</h1><p class="muted">Add your Firebase Web App configuration to <b>firebase-config.js</b>, enable Realtime Database and Anonymous Authentication, then reload.</p><p class="error">${String(e.message).replace(/[<>]/g,"")}</p></section></div>`}})();
