import {ref,set,get,update,remove,runTransaction,onDisconnect,serverTimestamp,onValue} from "https://www.gstatic.com/firebasejs/12.2.1/firebase-database.js";
import {getDb,getUid} from "./database.js";import {GAME,makePlayerState} from "../game/state.js";import {PLAYERS} from "../data/players.js";
const roomRef=c=>ref(getDb(),`rooms/${c}`),alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";const code5=()=>Array.from({length:5},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join("");const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
export async function createRoom(name,teamSize){const code=code5(),uid=getUid(),data={hostId:uid,status:"LOBBY",teamSize,createdAt:serverTimestamp(),lastActivityAt:serverTimestamp(),players:{[uid]:makePlayerState(uid,name,teamSize)},auction:{status:"IDLE",playerIds:shuffle(PLAYERS.map(p=>p.id)),playerIndex:-1,currentPlayerId:null,currentBid:0,highestBidderId:null,deadline:0}};if((await get(roomRef(code))).exists())return createRoom(name,teamSize);await set(roomRef(code),data);await armPresence(code,uid);return code}
export async function joinRoom(code,name){const snap=await get(roomRef(code));if(!snap.exists())throw Error("Room not found.");const room=snap.val(),ps=room.players||{},arr=Object.values(ps);if(room.status!=="LOBBY")throw Error("Auction has already started.");if(arr.length>=GAME.MAX_PLAYERS)throw Error("Room is full.");if(arr.some(p=>(p.name||"").trim().toLowerCase()===name.trim().toLowerCase()))throw Error("That name is already in the room.");const uid=getUid();await update(ref(getDb(),`rooms/${code}/players/${uid}`),makePlayerState(uid,name,room.teamSize));await update(roomRef(code),{lastActivityAt:serverTimestamp()});await armPresence(code,uid);return code}
async function armPresence(code,uid){const r=ref(getDb(),`rooms/${code}/players/${uid}/connected`);await onDisconnect(r).set(false);await set(r,true)}
export const subscribeRoom=(code,cb)=>onValue(roomRef(code),s=>cb(s.exists()?s.val():null));
export async function startGame(code){const snap=await get(roomRef(code)),room=snap.val(),uid=getUid();if(!room||room.hostId!==uid||Object.keys(room.players||{}).length<3)throw Error("Only the host can start with 3–5 players.");const first=room.auction.playerIds[0],p=PLAYERS.find(x=>x.id===first);await update(roomRef(code),{status:"AUCTION",lastActivityAt:serverTimestamp(),auction:{...room.auction,status:"LIVE",playerIndex:0,currentPlayerId:first,currentBid:p.basePrice-5,highestBidderId:null,deadline:Date.now()+GAME.AUCTION_SECONDS*1000}})}
export async function placeBid(code,amount){const uid=getUid();await runTransaction(roomRef(code),room=>{if(!room||room.status!=="AUCTION"||room.auction?.status!=="LIVE")return;const me=room.players?.[uid],p=PLAYERS.find(x=>x.id===room.auction.currentPlayerId);if(!me||!p||(me.squad||[]).includes(p.id))return;const min=Math.max(p.basePrice,Number(room.auction.currentBid||0)+5);if(!Number.isInteger(amount)||amount<min||amount>Number(me.budget||0))return;room.auction.currentBid=amount;room.auction.highestBidderId=uid;room.auction.deadline=Date.now()+GAME.BID_RESET_SECONDS*1000;room.lastActivityAt={".sv":"timestamp"};return room})}
export async function resolveAuction(code){const uid=getUid();await runTransaction(roomRef(code),room=>{if(!room||room.hostId!==uid||room.status!=="AUCTION"||room.auction?.status!=="LIVE"||Date.now()<Number(room.auction.deadline||0))return;const a=room.auction,p=PLAYERS.find(x=>x.id===a.currentPlayerId),winner=a.highestBidderId;if(!p)return;if(winner&&room.players?.[winner]){const pl=room.players[winner],price=Number(a.currentBid);if(price>pl.budget||(pl.squad||[]).includes(p.id))return;pl.budget-=price;pl.spent+=price;pl.squad=[...(pl.squad||[]),p.id]}const next=a.playerIndex+1;if(next>=a.playerIds.length){room.status="TEAM_REVIEW";room.auction.status="DONE";room.auction.currentPlayerId=null;room.auction.deadline=0}else{const np=PLAYERS.find(x=>x.id===a.playerIds[next]);room.auction.playerIndex=next;room.auction.currentPlayerId=np.id;room.auction.currentBid=np.basePrice-5;room.auction.highestBidderId=null;room.auction.deadline=Date.now()+GAME.AUCTION_SECONDS*1000}room.lastActivityAt={".sv":"timestamp"};return room})}
export const submitTeam=async code=>{const uid=getUid();await runTransaction(roomRef(code),room=>{if(!room||room.status!=="TEAM_REVIEW"||!room.players?.[uid])return;room.players[uid].submitted=true;room.lastActivityAt={".sv":"timestamp"};return room})};export const endRoom=code=>remove(roomRef(code));
